repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: ^(poetry.lock)
        args: ["-L", "ser,"]

  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.5
    hooks:
      - id: bandit
        exclude: ^(belay/pyboard.py)
        additional_dependencies: ["bandit[toml]"]
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile=black"]
        exclude: ^(belay/snippets/)
      - id: isort
        name: isort (cython)
        types: [cython]
        args: ["--profile=black"]
        exclude: ^(belay/snippets/)

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args:
          - "--target-version=py38"
          - "--target-version=py39"
          - "--target-version=py310"
        types: [python]
        exclude: ^(belay/snippets/)

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        exclude: ^(docs/source/How Belay Works.rst)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
      - id: nbqa-isort
        args: ["--profile=black"]
      - id: nbqa-black
        args:
          - "--target-version=py36"
          - "--target-version=py37"
          - "--target-version=py38"
          - "--target-version=py39"
          - "--target-version=py310"
      - id: nbqa-flake8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
        types: [text]
      - id: rst-inline-touching-normal
        types: [text]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
        exclude: ^(belay/pyboard.py)
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^LICENSE|\.(html|csv|txt|svg|py)$
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: \.(html|svg)$

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^(examples/|belay/snippets/|belay/pyboard.py)
        additional_dependencies:
          - flake8-2020
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-implicit-str-concat
          - flake8-use-pathlib

  - repo: https://github.com/fredrikaverpil/creosote.git
    rev: v2.3.7
    hooks:
      - id: creosote
        args:
          - "--venv=.venv"
          - "--paths=belay"
          - "--deps-file=pyproject.toml"
          - "--sections=tool.poetry.dependencies"
