from belay.cli._cache import cache_app
from belay.cli._clean import clean
from belay.cli._exec import exec
from belay.cli._info import info
from belay.cli._install import install
from belay.cli._new import new
from belay.cli._run import run
from belay.cli._select import select
from belay.cli._sync import sync
from belay.cli._terminal import terminal
from belay.cli._update import update
from belay.cli.main import app
