# Regular tests
#
# Use this to ensure your tests are passing on every push and PR (skipped on
# pushes which only affect documentation).
#
# You should make sure you run jobs on at least the *oldest* and the *newest*
# versions of python that your codebase is intended to support.

name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Check out Belay repository
        uses: actions/checkout@v3

      - name: Check out RP2040js repository
        uses: actions/checkout@v3
        with:
          repository: wokwi/rp2040js
          path: rp2040js

      - name: Cache $HOME/.local # Significantly speeds up Poetry Install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: dotlocal-${{ runner.os }}-${{ hashFiles('.github/workflows/tests.yml') }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache pi pico firmware
        id: cached-pi-pico-firmware
        uses: actions/cache@v3
        with:
          path: rp2040js/rp2-pico-20210902-v1.17.uf2
          key: pi-pico-rp2040js/rp2-pico-20210902-v1.17.uf2

      - name: Download Pi Pico firmware
        if: steps.cached-pi-pico-firmware.outputs.cache-hit != 'true'
        run: |
          cd rp2040js
          wget https://micropython.org/resources/firmware/rp2-pico-20210902-v1.17.uf2

      - name: Cache Node Modules
        id: cached-npm
        uses: actions/cache@v2
        with:
          path: rp2040js/node_modules
          key: modules-${{ hashFiles('rp2040js/package-lock.json') }}

      - name: Install rp2040js
        if: steps.cached-npm.outputs.cache-hit != 'true'
        run: |
          cd rp2040js
          npm install

      - name: Install Belay
        run: poetry install --no-interaction

      - name: Sanity check with flake8
        run: |
          source .venv/bin/activate
          # stop the build if there are Python syntax errors or undefined names
          python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          python -m flake8 . --count --exit-zero --statistics

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest --cov=belay --cov-report term --cov-report xml --cov-config .coveragerc --junitxml=testresults.xml tests tests/integration
          coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          env_vars: OS,PYTHON
          name: Python ${{ matrix.python-version }} on ${{ runner.os }}

      #----------------------------------------------
      #            make sure docs build
      #----------------------------------------------
      - name: Build HTML docs
        run: |
          source .venv/bin/activate
          sphinx-build -b html docs/source/ docs/build/html
